import type { Port } from "../data";

// Approximate historical harbour / river-trading locations in WGS84 degrees.
// Era is a playable access window, not the city's foundation date. Regional
// polities are deliberately broad because one place can span several dynasties.
type PortRow = [string, string, string, number, number, number, string, string, string, string?];
const rows: PortRow[] = [
  ["sidon", "西顿", "黎凡特海岸", 35.37, 33.56, 1, "med", "dye glass cedar", "grain copper linen"],
  ["akka", "阿卡", "黎凡特海岸", 35.08, 32.92, 2, "med", "oil pottery", "grain copper tin"],
  ["jaffa", "雅法", "黎凡特海岸", 34.75, 32.05, 2, "med", "oil wine pottery", "cedar copper linen"],
  ["athens", "比雷埃夫斯", "阿提卡", 23.64, 37.94, 3, "med", "pottery oil wine", "grain tin cedar"],
  ["corinth", "科林斯", "科林斯湾", 22.92, 37.94, 3, "med", "pottery oil", "grain copper dye"],
  ["rhodes", "罗得岛", "爱琴海", 28.22, 36.44, 3, "med", "wine oil pottery", "grain linen pepper", "island"],
  ["miletus", "米利都", "安纳托利亚西岸", 27.28, 37.53, 3, "med", "wine pottery", "grain tin linen"],
  ["ephesus", "以弗所", "安纳托利亚西岸", 27.34, 37.94, 3, "med", "pottery wine", "grain glass pepper"],
  ["smyrna", "士麦那", "安纳托利亚西岸", 27.13, 38.43, 3, "med", "wine oil", "grain iron silk"],
  ["sinope", "锡诺普", "黑海南岸", 35.15, 42.02, 3, "blacksea", "iron grain", "oil wine pottery"],
  ["trebizond", "特拉布宗", "黑海南岸", 39.72, 41.01, 4, "blacksea", "iron silk", "salt glass oil"],
  ["chersonesus", "赫尔松尼索斯", "克里米亚半岛", 33.49, 44.61, 3, "blacksea", "grain salt", "wine oil pottery"],
  ["caffa", "卡法", "克里米亚半岛", 35.39, 45.03, 7, "blacksea", "grain salt", "silk glass pepper"],
  ["thessaloniki", "塞萨洛尼基", "爱琴海北岸", 22.94, 40.63, 3, "med", "grain wine", "silk pepper glass"],
  ["syracuse", "锡拉库萨", "西西里岛", 15.29, 37.07, 3, "med", "grain wine oil", "iron tin glass", "island"],
  ["palermo", "巴勒莫", "西西里岛", 13.36, 38.12, 3, "med", "grain oil salt", "iron linen pepper", "island"],
  ["messina", "墨西拿", "西西里海峡", 15.55, 38.19, 3, "med", "wine salt", "grain silk iron", "island"],
  ["naples", "那不勒斯", "意大利南岸", 14.27, 40.84, 3, "med", "wine pottery oil", "grain silk pepper"],
  ["brindisi", "布林迪西", "意大利东岸", 17.94, 40.64, 3, "med", "oil wine", "grain glass silk"],
  ["ravenna", "拉文纳", "亚得里亚海", 12.28, 44.48, 4, "med", "salt grain glass", "silk pepper cedar"],
  ["genoa", "热那亚", "利古里亚海", 8.93, 44.41, 6, "med", "glass oil wine", "silk pepper grain"],
  ["pisa", "比萨", "托斯卡纳海岸", 10.29, 43.68, 6, "med", "wine oil iron", "grain silk pepper"],
  ["ragusa", "拉古萨", "达尔马提亚海岸", 18.11, 42.64, 6, "med", "salt iron", "grain silk glass"],
  ["split", "斯普利特", "达尔马提亚海岸", 16.44, 43.51, 4, "med", "wine oil salt", "grain silk pottery"],
  ["marseille", "马赛", "普罗旺斯海岸", 5.37, 43.3, 3, "med", "wine oil salt", "grain tin pepper"],
  ["barcelona", "巴塞罗那", "加泰罗尼亚海岸", 2.18, 41.38, 6, "med", "wine oil iron", "silk pepper grain"],
  ["valencia", "瓦伦西亚", "伊比利亚东岸", -0.32, 39.45, 6, "med", "pottery wine oil", "grain iron silk"],
  ["malaga", "马拉加", "安达卢西亚海岸", -4.42, 36.72, 3, "med", "wine oil salt", "grain iron linen"],
  ["ceuta", "休达", "直布罗陀海峡", -5.31, 35.9, 5, "med", "salt oil", "grain iron silk"],
  ["tangier", "丹吉尔", "摩洛哥海岸", -5.81, 35.79, 3, "atlantic", "salt oil", "grain linen copper"],
  ["algiers", "阿尔及尔", "马格里布海岸", 3.06, 36.77, 6, "med", "grain oil", "iron linen glass"],
  ["tunis", "突尼斯", "突尼斯湾", 10.3, 36.8, 5, "med", "oil grain salt", "iron silk glass"],
  ["tripoli", "的黎波里", "利比亚海岸", 13.19, 32.89, 3, "med", "salt oil", "grain linen copper"],
  ["cyrene", "阿波罗尼亚", "昔兰尼加海岸", 21.97, 32.9, 3, "med", "grain wine", "oil iron pottery"],
  ["famagusta", "法马古斯塔", "塞浦路斯东岸", 33.95, 35.12, 6, "med", "copper salt wine", "grain silk pepper", "island"],
  ["salamis", "萨拉米斯", "塞浦路斯东岸", 33.9, 35.18, 2, "med", "copper pottery", "grain tin linen", "island"],
  ["porto", "波尔图", "葡萄牙杜罗河口", -8.67, 41.15, 6, "atlantic", "wine salt", "iron grain silk"],
  ["seville", "塞维利亚", "瓜达尔基维尔河", -6, 37.38, 8, "atlantic", "oil wine pottery", "silver sugar pepper", "river"],
  ["bordeaux", "波尔多", "法国加龙河口", -0.55, 44.84, 6, "atlantic", "wine salt", "iron linen pepper", "river"],
  ["nantes", "南特", "卢瓦尔河口", -1.55, 47.2, 6, "atlantic", "salt grain wine", "iron linen sugar", "river"],
  ["la-rochelle", "拉罗谢尔", "比斯开湾", -1.15, 46.16, 6, "atlantic", "salt wine", "grain iron linen"],
  ["bristol", "布里斯托尔", "不列颠西岸", -2.6, 51.45, 6, "atlantic", "iron tin linen", "wine oil salt", "river"],
  ["plymouth", "普利茅斯", "英吉利海峡", -4.14, 50.37, 7, "atlantic", "tin salt", "wine oil linen"],
  ["dublin", "都柏林", "爱尔兰海", -6.24, 53.35, 5, "atlantic", "linen grain", "wine salt iron", "river"],
  ["edinburgh", "利斯", "苏格兰福斯湾", -3.17, 55.98, 6, "northsea", "linen salt", "wine iron grain"],
  ["bruges", "布鲁日", "佛兰德斯海岸", 3.2, 51.21, 6, "northsea", "linen glass", "wine grain pepper"],
  ["antwerp", "安特卫普", "斯海尔德河", 4.4, 51.22, 7, "northsea", "linen glass iron", "pepper sugar silver", "river"],
  ["hamburg", "汉堡", "易北河口", 9.97, 53.55, 6, "northsea", "grain iron linen", "wine salt pepper", "river"],
  ["bremen", "不来梅", "威悉河口", 8.8, 53.08, 6, "northsea", "grain linen", "wine salt iron", "river"],
  ["bergen", "卑尔根", "挪威西岸", 5.32, 60.4, 6, "northsea", "iron", "grain salt linen"],
  ["copenhagen", "哥本哈根", "厄勒海峡", 12.6, 55.68, 6, "baltic", "grain salt", "wine iron linen"],
  ["lubeck", "吕贝克", "波罗的海南岸", 10.7, 53.87, 6, "baltic", "salt grain", "wine linen pepper"],
  ["gdansk", "格但斯克", "维斯瓦河口", 18.65, 54.35, 6, "baltic", "grain linen", "wine salt iron"],
  ["riga", "里加", "道加瓦河口", 24.11, 56.95, 6, "baltic", "linen grain", "salt wine iron"],
  ["tallinn", "塔林", "芬兰湾南岸", 24.75, 59.45, 6, "baltic", "grain linen", "salt wine glass"],
  ["stockholm", "斯德哥尔摩", "瑞典东岸", 18.07, 59.33, 6, "baltic", "copper iron", "grain salt wine"],
  ["visby", "维斯比", "哥特兰岛", 18.3, 57.64, 6, "baltic", "grain salt", "linen wine iron", "island"],
  ["novgorod", "诺夫哥罗德", "沃尔霍夫河商路", 31.28, 58.52, 6, "baltic", "linen grain", "salt wine iron", "river"],
  ["arwad", "阿尔瓦德", "黎凡特近海", 35.86, 34.86, 1, "med", "cedar pottery salt", "grain copper tin", "island"],
  ["qana", "卡纳", "哈德拉毛海岸", 48.33, 14.02, 3, "indian", "salt", "grain linen glass"],
  ["jeddah", "吉达", "红海东岸", 39.17, 21.49, 5, "redsea", "salt", "grain cotton pepper"],
  ["suakin", "萨瓦金", "红海西岸", 37.33, 19.11, 6, "redsea", "salt gems", "grain cotton glass"],
  ["massawa", "马萨瓦", "厄立特里亚海岸", 39.46, 15.61, 5, "redsea", "salt gems", "grain cotton copper"],
  ["mocha", "摩卡", "也门红海岸", 43.25, 13.32, 8, "redsea", "coffee salt", "grain cotton porcelain"],
  ["muscat", "马斯喀特", "阿曼海岸", 58.59, 23.61, 5, "gulf", "copper salt", "grain cotton porcelain"],
  ["sohar", "苏哈尔", "阿曼海岸", 56.75, 24.36, 5, "gulf", "copper salt", "grain cotton pepper"],
  ["qishm", "格什姆", "波斯湾海峡", 56.27, 26.95, 5, "gulf", "salt ivory-sub", "grain cotton iron", "island"],
  ["mogadishu", "摩加迪沙", "索马里海岸", 45.35, 2.04, 6, "indian", "cotton salt", "grain porcelain iron"],
  ["mombasa", "蒙巴萨", "斯瓦希里海岸", 39.67, -4.05, 6, "indian", "salt gems", "cotton porcelain iron"],
  ["zanzibar", "桑给巴尔", "东非近海", 39.2, -6.16, 6, "indian", "salt gems", "cotton porcelain iron", "island"],
  ["sofala", "索法拉", "莫桑比克海岸", 34.73, -20.17, 6, "indian", "gems", "cotton iron porcelain"],
  ["mozambique", "莫桑比克岛", "莫桑比克海峡", 40.73, -15.04, 6, "indian", "salt gems", "cotton iron grain", "island"],
  ["cape-town", "开普敦", "好望角", 18.42, -33.92, 9, "atlantic", "wine grain", "iron cotton tea"],
  ["elmina", "埃尔米纳", "几内亚湾", -1.35, 5.08, 8, "westafrica", "gems", "cotton iron salt"],
  ["accra", "阿克拉", "几内亚湾", -0.2, 5.55, 8, "westafrica", "gems", "cotton iron salt"],
  ["benin", "贝宁河港", "贝宁湾", 5.32, 5.67, 8, "westafrica", "pepper", "copper iron cotton", "river"],
  ["bonny", "邦尼", "尼日尔三角洲", 7.15, 4.45, 8, "westafrica", "salt", "iron copper cotton"],
  ["arguin", "阿尔金", "毛里塔尼亚海岸", -16.45, 20.6, 8, "westafrica", "salt", "grain cotton iron", "island"],
  ["ribeira-grande", "里贝拉格兰德", "佛得角群岛", -23.61, 14.92, 8, "atlantic", "salt sugar", "grain iron linen", "island"],
  ["funchal", "丰沙尔", "马德拉群岛", -16.91, 32.65, 8, "atlantic", "wine sugar", "grain iron linen", "island"],
  ["las-palmas", "拉斯帕尔马斯", "加那利群岛", -15.41, 28.14, 8, "atlantic", "sugar wine", "grain iron linen", "island"],
  ["angra", "英雄港", "亚速尔群岛", -27.22, 38.65, 8, "atlantic", "grain wine", "iron sugar linen", "island"],
  ["cambay", "坎贝", "古吉拉特海湾", 72.62, 22.3, 5, "indian", "cotton gems", "copper silver porcelain"],
  ["bharuch", "婆鲁迦车", "纳尔默达河口", 72.98, 21.71, 3, "indian", "gems pepper", "copper wine glass"],
  ["chaul", "绍尔", "康坎海岸", 72.93, 18.55, 6, "indian", "cotton pepper", "copper silver porcelain"],
  ["cochin", "科钦", "马拉巴尔海岸", 76.27, 9.97, 7, "indian", "pepper cinnamon", "silver cotton porcelain"],
  ["quilon", "奎隆", "马拉巴尔海岸", 76.59, 8.89, 5, "indian", "pepper cinnamon", "silver copper porcelain"],
  ["galle", "加勒", "斯里兰卡南岸", 80.22, 6.03, 6, "indian", "cinnamon gems", "cotton iron porcelain", "island"],
  ["colombo", "科伦坡", "斯里兰卡西岸", 79.84, 6.94, 6, "indian", "cinnamon gems", "cotton iron silver", "island"],
  ["masulipatnam", "马苏利帕特南", "科罗曼德尔海岸", 81.13, 16.17, 7, "indian", "cotton", "silver copper cloves"],
  ["nagapattinam", "纳加帕蒂南", "泰米尔海岸", 79.85, 10.77, 6, "indian", "cotton salt", "copper silver cloves"],
  ["pulicat", "普利卡特", "科罗曼德尔海岸", 80.32, 13.42, 8, "indian", "cotton", "silver copper pepper"],
  ["satgaon", "萨特冈", "孟加拉三角洲", 88.4, 22.98, 6, "indian", "cotton grain", "copper silver spices", "river"],
  ["chittagong", "吉大港", "孟加拉湾东北岸", 91.8, 22.33, 6, "indian", "cotton grain", "copper silver porcelain"],
  ["pegu", "勃固", "伊洛瓦底江口商路", 96.48, 17.33, 6, "southeast", "gems grain", "cotton silver porcelain", "river"],
  ["martaban", "马达班", "缅甸南岸", 97.6, 16.53, 7, "southeast", "pottery grain", "cotton silver pepper"],
  ["tenasserim", "丹那沙林", "马来半岛西岸", 98.4, 12.08, 7, "southeast", "tin pepper", "cotton silver porcelain"],
  ["kedah", "吉打", "马来半岛西岸", 100.32, 5.69, 5, "southeast", "tin pepper", "cotton silk porcelain"],
  ["aceh", "亚齐", "苏门答腊北岸", 95.32, 5.56, 8, "southeast", "pepper", "cotton silver porcelain"],
  ["barus", "巴鲁斯", "苏门答腊西岸", 98.4, 2.02, 5, "southeast", "pepper", "cotton copper porcelain"],
  ["banten", "万丹", "爪哇岛西岸", 106.16, -6.04, 8, "southeast", "pepper sugar", "silver cotton porcelain"],
  ["gresik", "格雷西克", "爪哇岛北岸", 112.65, -7.16, 7, "southeast", "grain salt", "cotton copper porcelain"],
  ["makassar", "望加锡", "苏拉威西南岸", 119.41, -5.14, 8, "southeast", "grain cloves", "cotton silver porcelain"],
  ["ternate", "特尔纳特", "马鲁古群岛", 127.38, 0.79, 7, "southeast", "cloves", "grain iron cotton", "island"],
  ["banda", "班达", "班达群岛", 129.9, -4.52, 7, "southeast", "nutmeg", "grain iron cotton", "island"],
  ["hoi-an", "会安", "越南中部海岸", 108.34, 15.88, 8, "southeast", "silk sugar", "copper silver porcelain"],
  ["ayutthaya", "阿瑜陀耶", "湄南河商路", 100.57, 14.36, 7, "southeast", "grain sugar", "copper silver silk", "river"],
  ["pattani", "北大年", "泰国湾", 101.25, 6.87, 8, "southeast", "tin pepper", "cotton silver porcelain"],
  ["brunei", "文莱", "婆罗洲北岸", 114.96, 4.89, 7, "southeast", "pepper", "cotton copper porcelain"],
  ["ningbo", "明州", "浙江沿海", 121.55, 29.87, 5, "china", "silk tea porcelain", "pepper silver gems"],
  ["hangzhou", "杭州", "钱塘江商路", 120.19, 30.24, 6, "china", "silk tea porcelain", "pepper silver cloves", "river"],
  ["yangzhou", "扬州", "长江与运河", 119.43, 32.39, 5, "china", "silk salt", "pepper gems copper", "river"],
  ["fuzhou", "福州", "福建闽江口", 119.45, 26, 6, "china", "tea porcelain", "silver pepper cloves"],
  ["dengzhou", "登州", "山东半岛", 120.75, 37.81, 5, "china", "silk salt", "gems pepper copper"],
  ["nanjing", "南京", "长江下游", 118.76, 32.08, 7, "china", "silk porcelain paper", "silver pepper cloves", "river"],
  ["macao", "澳门", "珠江口", 113.55, 22.19, 8, "china", "silk porcelain tea", "silver pepper cotton"],
  ["tamsui", "淡水", "台湾北岸", 121.44, 25.17, 9, "china", "sugar grain", "iron cotton porcelain"],
  ["busan", "釜山", "朝鲜半岛南岸", 129.04, 35.1, 7, "japan", "paper pottery", "copper silk pepper"],
  ["hakata", "博多", "日本九州北岸", 130.4, 33.6, 6, "japan", "copper salt", "silk porcelain tea"],
  ["sakai", "堺", "日本大阪湾", 135.46, 34.57, 7, "japan", "iron copper", "silk porcelain pepper"],
  ["nagasaki", "长崎", "日本九州西岸", 129.87, 32.75, 8, "japan", "silver copper", "silk sugar porcelain"],
  ["naha", "那霸", "琉球群岛", 127.67, 26.21, 7, "japan", "salt sugar", "silk porcelain iron", "island"],
  ["acapulco", "阿卡普尔科", "墨西哥太平洋岸", -99.88, 16.85, 8, "pacific", "silver cocoa", "silk porcelain iron"],
  ["cartagena", "卡塔赫纳", "加勒比海南岸", -75.55, 10.4, 8, "caribbean", "cocoa tobacco", "iron linen wine"],
  ["portobelo", "贝洛港", "巴拿马加勒比岸", -79.65, 9.55, 8, "caribbean", "silver cocoa", "iron linen wine"],
  ["panama", "巴拿马城", "巴拿马太平洋岸", -79.5, 8.96, 8, "pacific", "silver cocoa", "iron linen wine"],
  ["callao", "卡亚俄", "秘鲁海岸", -77.15, -12.06, 8, "pacific", "silver", "iron wine silk"],
  ["guayaquil", "瓜亚基尔", "厄瓜多尔海岸", -79.88, -2.19, 8, "pacific", "cocoa", "iron wine cotton"],
  ["valparaiso", "瓦尔帕莱索", "智利海岸", -71.62, -33.04, 8, "pacific", "wine grain copper", "iron silk sugar"],
  ["salvador", "萨尔瓦多", "巴西东北海岸", -38.52, -12.97, 8, "atlantic-americas", "sugar tobacco", "iron linen wine"],
  ["recife", "累西腓", "巴西东北海岸", -34.87, -8.06, 8, "atlantic-americas", "sugar", "iron linen wine"],
  ["rio", "里约热内卢", "巴西东南海岸", -43.17, -22.9, 8, "atlantic-americas", "sugar", "iron linen wine"],
  ["buenos-aires", "布宜诺斯艾利斯", "拉普拉塔河口", -58.36, -34.61, 8, "atlantic-americas", "grain silver", "iron linen wine"],
  ["san-juan", "圣胡安", "波多黎各", -66.12, 18.47, 8, "caribbean", "sugar tobacco", "iron linen wine", "island"],
  ["bridgetown", "布里奇敦", "巴巴多斯", -59.62, 13.1, 9, "caribbean", "sugar", "iron linen grain", "island"],
  ["port-royal", "皇家港", "牙买加", -76.84, 17.94, 9, "caribbean", "sugar cocoa", "iron linen wine", "island"],
  ["willemstad", "威廉斯塔德", "库拉索岛", -68.94, 12.11, 9, "caribbean", "salt", "grain linen iron", "island"],
  ["boston", "波士顿", "新英格兰海岸", -71.05, 42.35, 9, "atlantic-americas", "iron grain", "sugar wine linen"],
  ["new-amsterdam", "新阿姆斯特丹", "哈得孙河口", -74.01, 40.7, 9, "atlantic-americas", "grain", "sugar wine linen"],
  ["quebec", "魁北克", "圣劳伦斯河", -71.2, 46.81, 9, "atlantic-americas", "grain", "iron wine linen", "river"],
  ["st-johns", "圣约翰斯", "纽芬兰岛", -52.71, 47.56, 8, "atlantic-americas", "salt", "grain iron linen", "island"],
];

const climateFor = (latitude: number, basin: string) => {
  if (basin === "med") return "地中海气候";
  if (["gulf", "redsea"].includes(basin)) return "干旱海岸";
  if (["indian", "southeast", "china"].includes(basin) && Math.abs(latitude) < 30) return "季风海岸";
  if (Math.abs(latitude) < 23.5) return "热带海岸";
  if (Math.abs(latitude) > 55) return "寒温带海岸";
  return "温带海岸";
};

export const extendedPorts: Port[] = rows.map(([id, name, region, lon, lat, era, basin, produces, demands, type]) => ({
  id, name, polity: `${region}商人`, region, x: lon / 180, y: lat / 90, era, basin,
  produces: produces.split(" "), demands: demands.replace("spices", "pepper").split(" "),
  danger: ["caribbean", "southeast", "westafrica"].includes(basin) ? 0.26 : 0.18,
  climate: climateFor(lat, basin), specialty: region,
  type: (type || "coastal") as Port["type"],
}));
