const { chromium } = require('C:/Users/刘锦烋/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({headless:true,args:['--enable-unsafe-swiftshader','--use-angle=swiftshader','--disable-webgpu']});
 const errors=[];
 try {
 const page=await browser.newPage({viewport:{width:1440,height:960},deviceScaleFactor:1,serviceWorkers:'block'});
 page.setDefaultTimeout(20000);
 await page.addInitScript(()=>{Object.defineProperty(navigator,'gpu',{value:undefined});localStorage.setItem('remote-trade-quality','low');});
 await page.addInitScript(()=>{
   const nativeRAF=window.requestAnimationFrame.bind(window);
   let paused=false; const pending=[];
   window.requestAnimationFrame=callback=>nativeRAF(time=>{if(paused)pending.push(callback);else callback(time);});
   window.__pauseCapture=value=>{paused=value;if(!value)pending.splice(0).forEach(callback=>nativeRAF(callback));};
 });
 const capture=async path=>{
   if(process.env.SKIP_DESKTOP_SHOTS==='1' && !path.includes('mobile'))return;
   await page.evaluate(()=>new Promise(resolve=>{window.__pauseCapture(true);setTimeout(resolve,150);}));
   try {await page.screenshot({path,timeout:45000});} finally {await page.evaluate(()=>window.__pauseCapture(false));}
 };
 page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 await page.goto('http://127.0.0.1:4173/');
 await page.waitForSelector('canvas');await page.waitForFunction(()=>document.querySelector('#eraLabel').textContent.includes('01 /'));
 await capture('outputs/harbor-welcome.png');
 await page.locator('#startGame').click();
 await page.locator('#welcome').waitFor({state:'hidden'});
 await page.locator('#marketNews').waitFor({state:'visible'});
 await page.locator('#pause').click();
 const initialClue=await page.locator('#newsClue').innerText();
 if(!initialClue || /\d+%|买入|卖出|必赚/.test(initialClue))throw Error('News does not contain a subtle clue');
 await capture('outputs/harbor-weather-news.png');
 await page.locator('#readNews').click();
 await page.locator('.intelligence-card').waitFor({state:'visible'});
 if(!(await page.locator('.intelligence-list').innerText()).includes(initialClue))throw Error('News not archived');
 await capture('outputs/harbor-intelligence.png');
 await page.locator('#closeDrawer').click();
 if(await page.locator('#marketNews').isVisible())throw Error('Read news reappeared');
 await capture('outputs/harbor-map.png');
 await page.locator('.bottom-dock [data-panel="market"]').click();
 const unitPrice=await page.locator('[data-unit-buy="grain"]').innerText();
 if(!unitPrice.includes('金币／袋'))throw Error('Market unit price is not explicit');
 await page.locator('[data-quantity="10"]').click();
 if(unitPrice!==await page.locator('[data-unit-buy="grain"]').innerText())throw Error('Quantity changed unit-price display');
 await page.locator('[data-quantity="5"]').click();
 const quotedCost=Number((await page.locator('[data-buy="grain"] small').innerText()).replace(/[^\d]/g,''));
 const cash=await page.locator('#cash').innerText();await page.locator('[data-buy="grain"]').click();
 if(cash===await page.locator('#cash').innerText())throw Error('Purchase did not change cash');
 if(Number(cash.replaceAll(',',''))-Number((await page.locator('#cash').innerText()).replaceAll(',',''))!==quotedCost)throw Error('Preview cost differs from transaction');
 await page.locator('.trade-receipt').waitFor({state:'visible'});
 await page.locator('[data-market-filter="held"]').click();
 if(!await page.locator('[data-good="grain"]').isVisible())throw Error('Held cargo filter lost purchase');
 await page.locator('[data-market-filter="all"]').click();
 await capture('outputs/harbor-market.png');
 await page.locator('.bottom-dock [data-panel="route"]').click();
 await page.locator('[data-destination="byblos"]').click();
 await page.locator('#sail').click();await page.locator('#drawer').waitFor({state:'hidden'});
 await page.locator('[data-speed="4"]').click();
 const firstDay=await page.locator('#dayLabel').innerText();
 await page.waitForFunction(first=>!!document.querySelector('#dayLabel') && document.querySelector('#dayLabel').textContent!==first,firstDay,{timeout:25000});
 await page.waitForFunction(()=>document.querySelector('#placeName')?.textContent==='比布鲁斯',null,{timeout:60000});
 await page.waitForFunction(()=>Number(document.querySelector('#dayLabel')?.textContent.match(/\d+/)?.[0])>=5,null,{timeout:25000});
 await page.locator('#marketNews').waitFor({state:'visible'});
 await page.locator('#dismissNews').click();
 await page.locator('[data-speed="4"]').click();
 if(await page.locator('#marketNews').isVisible())throw Error('Dismissed news replayed after HUD update');
 await page.locator('.bottom-dock [data-panel="market"]').click();await page.locator('[data-sell="grain"]').click();
 if(!(await page.locator('.trade-receipt').innerText()).includes('货物差额'))throw Error('Sale receipt missing trading result');
 if(!(await page.locator('#guide').innerText()).includes('家族成长'))throw Error('No next goal after first sale');
 await page.locator('#openAccounts').click();
 if(!(await page.locator('.account-summary').innerText()).includes('销售收入'))throw Error('Trade ledger unavailable');
 await page.locator('.bottom-dock [data-panel="market"]').click();
 const drawerDay=await page.locator('#dayLabel').innerText();
 await page.waitForTimeout(5200);if(drawerDay!==await page.locator('#dayLabel').innerText())throw Error('Time changed with drawer open');
 await page.locator('#closeDrawer').click();await page.locator('#pause').click();
 const pauseDay=await page.locator('#dayLabel').innerText();await page.waitForTimeout(5200);if(pauseDay!==await page.locator('#dayLabel').innerText())throw Error('Paused time changed');
 await page.locator('[data-panel="settings"]').click();await page.locator('#save').click();
 await page.waitForFunction(()=>document.querySelector('#toast').textContent==='航程已保存到本机');
 const savedCash=await page.locator('#cash').innerText();
 const storedEvents=await page.evaluate(()=>JSON.parse(JSON.parse(localStorage.getItem('remote-trade-save-v1')).snapshots[0].serialized).marketEvents);
 if(storedEvents.length<2)throw Error('Timed news not generated and saved');
 await page.reload();await page.locator('#continueGame').waitFor({state:'visible'});await page.locator('#continueGame').click();await page.locator('#welcome').waitFor({state:'hidden'});if(savedCash!==await page.locator('#cash').innerText())throw Error('Save restore mismatch');
 await page.locator('#pause').click();
 await page.setViewportSize({width:390,height:844});await capture('outputs/harbor-mobile.png');
 await page.locator('#marketNews').waitFor({state:'visible'});
 const newsBounds=await page.locator('#marketNews').boundingBox();
 const timeBounds=await page.locator('.time-bar').boundingBox();
 if(newsBounds.x<0 || newsBounds.x+newsBounds.width>390 || newsBounds.y<timeBounds.y+timeBounds.height)throw Error('Mobile news overlaps controls');
 await page.locator('#readNews').click();
 const restoredClues=await page.locator('.intelligence-list').innerText();
 for(const e of storedEvents)if(!restoredClues.includes(e.clue))throw Error('News archive lost on restore');
 await capture('outputs/harbor-mobile-intelligence.png');
 await page.locator('#closeDrawer').click();
 await page.locator('.bottom-dock [data-panel="market"]').click();
 const mobilePrices=await page.locator('[data-unit-buy="grain"]').boundingBox();
 if(!mobilePrices || mobilePrices.x+mobilePrices.width>390)throw Error('Mobile price column clipped');
 await capture('outputs/harbor-mobile-market.png');
 await page.locator('#closeDrawer').click();
 await page.locator('.bottom-dock [data-panel="history"]').click();
 if(await page.locator('.era-entry').count()!==11)throw Error('Incomplete timeline');
 await capture('outputs/harbor-mobile-drawer.png');
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);if(overflow)throw Error('Mobile horizontal overflow');
 const checks=['start','subtle-news','news-dismiss','news-archive','explicit-unit-prices','quantity-quote','exact-purchase-total','cargo-filter','buy','route','automatic-time','arrival','sale-receipt','next-goal','trade-ledger','sell','drawer-pause','manual-pause','save-load','news-save-load','mobile-news-layout','mobile-unit-prices','mobile','all-eras'];
 console.log(JSON.stringify({errors,cash:savedCash,ports:39,checks},null,2));
 fs.writeFileSync('outputs/browser-check.json',JSON.stringify({errors,passed:errors.length===0,checks},null,2));
 if(errors.length)process.exitCode=1;
 } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
