import { majorPorts } from "./catalog/major-ports";
import { extendedPorts } from "./catalog/ports";
import { extendedGoods } from "./catalog/goods";
import { createMarketCatalog } from "./catalog/markets";

export type Era = {
  id: string;
  title: string;
  years: string;
  subtitle: string;
  tech: string;
  color: string;
  threshold: number;
  startYear: number;
  shipName: string;
};
export type Good = {
  id: string;
  name: string;
  icon: string;
  base: number;
  unit: string;
  color: string;
  era: number;
  category?: string;
  description?: string;
  originRegions?: string[];
  originPortIds?: string[];
  familyId?: string;
};
export type Port = {
  id: string;
  name: string;
  polity: string;
  region: string;
  x: number;
  y: number;
  produces: string[];
  demands: string[];
  era: number;
  danger: number;
  basin: string;
  climate?: string;
  specialty?: string;
  type?: "coastal" | "river" | "island";
};
export type Origin = {
  id: string;
  title: string;
  portId: string;
  region: string;
  note: string;
  perk: string;
  capital: number;
  goods: Record<string, number>;
  accent: string;
  era: number;
};
export const eras: Era[] = [
  [
    "river",
    "河口与海湾贸易",
    "前 3000 — 前 1800",
    "尼罗河、两河与印度河的早期贸易",
    "木帆船 · 标准度量",
    0,
    -3000,
    "河口帆船",
  ],
  [
    "bronze",
    "青铜海路",
    "前 1800 — 前 1200",
    "铜锡、黎凡特木材与爱琴海港邦",
    "缝合木船 · 季风观察",
    3000,
    -1800,
    "青铜时代商船",
  ],
  [
    "iron",
    "铁器与城邦",
    "前 1200 — 前 600",
    "腓尼基商人与地中海贸易据点",
    "桨帆船 · 港口关税",
    8500,
    -1200,
    "双桅桨帆商船",
  ],
  [
    "classical",
    "古典帝国商路",
    "前 600 — 公元 200",
    "地中海、红海与印度洋商路",
    "远洋帆桨船 · 护航",
    22000,
    -600,
    "古典远洋商船",
  ],
  [
    "late-antique",
    "晚古代海网",
    "200 — 700",
    "拜占庭、萨珊与东非海岸",
    "季风历法 · 海上驿站",
    65000,
    200,
    "晚古代海船",
  ],
  [
    "monsoon",
    "季风商网",
    "700 — 1000",
    "阿拉伯海与唐代港口",
    "三角帆 · 商业票据",
    150000,
    700,
    "三角帆远洋船",
  ],
  [
    "medieval",
    "中世纪远洋",
    "1000 — 1300",
    "宋代海贸与印度洋航线",
    "海船水密舱 · 航海罗盘",
    450000,
    1000,
    "远洋福船",
  ],
  [
    "crossroads",
    "跨洲商网",
    "1300 — 1450",
    "威尼斯、泉州与霍尔木兹",
    "商港网络 · 海上保险",
    1200000,
    1300,
    "跨洲商船",
  ],
  [
    "oceanic",
    "大洋航路",
    "1450 — 1600",
    "大西洋与跨洋贸易网络",
    "卡拉维尔 · 克拉克",
    3000000,
    1450,
    "克拉克远洋船",
  ],
  [
    "global",
    "全球商网",
    "1600 — 1700",
    "马尼拉、月港与远洋商会",
    "盖伦船 · 远洋保险",
    9000000,
    1600,
    "盖伦商船",
  ],
  [
    "early-modern",
    "近代早期",
    "1700 — 1750",
    "全球市场联动与商贸金融",
    "大型商船 · 商业账簿",
    25000000,
    1700,
    "大型远洋商船",
  ],
].map(
  ([id, title, years, subtitle, tech, threshold, startYear, shipName], i) => ({
    id: String(id),
    title: String(title),
    years: String(years),
    subtitle: String(subtitle),
    tech: String(tech),
    threshold: Number(threshold),
    startYear: Number(startYear),
    shipName: String(shipName),
    color: ["#c5ab74", "#b48b62", "#a39b7b", "#87a190"][i % 4],
  }),
);
const good = (
  id: string,
  name: string,
  base: number,
  era: number,
  color: string,
  unit = "箱",
): Good => ({ id, name, icon: name[0], base, era, color, unit });
export const goods: Good[] = [
  good("grain", "谷物", 18, 0, "#d9c286", "袋"),
  good("salt", "盐", 26, 0, "#e2dfc7", "罐"),
  good("linen", "亚麻", 42, 0, "#c8c5a3", "捆"),
  good("copper", "铜锭", 82, 0, "#b98565", "块"),
  good("cedar", "雪松木", 66, 0, "#8fa783", "段"),
  good("pottery", "陶器", 58, 0, "#c48b62"),
  good("oil", "橄榄油", 74, 1, "#c2bc6a", "罐"),
  good("tin", "锡锭", 105, 1, "#b6c9c0", "块"),
  good("dye", "紫染料", 145, 1, "#ae8ba8", "匣"),
  good("wine", "葡萄酒", 98, 2, "#b48679", "桶"),
  good("iron", "铁材", 84, 2, "#95a49d"),
  good("glass", "玻璃器", 130, 2, "#87b5b0"),
  good("silk", "丝绸", 195, 3, "#d4a586", "匹"),
  good("pepper", "胡椒", 145, 3, "#aab47c", "袋"),
  good("cinnamon", "肉桂", 168, 3, "#b89568"),
  good("gems", "宝石", 420, 4, "#84b8aa", "匣"),
  good("ivory-sub", "珍珠", 340, 4, "#e7d9b9", "匣"),
  good("porcelain", "瓷器", 245, 5, "#c0d6d0"),
  good("tea", "茶叶", 175, 5, "#8cb088"),
  good("cotton", "棉布", 108, 5, "#d1c5a1", "匹"),
  good("cloves", "丁香", 280, 6, "#b9a28c"),
  good("nutmeg", "肉豆蔻", 245, 6, "#ad926c"),
  good("paper", "纸张", 90, 7, "#e0d4ad"),
  good("sugar", "蔗糖", 130, 8, "#d6cbaa", "袋"),
  good("cocoa", "可可", 175, 8, "#b1886f", "袋"),
  good("tobacco", "烟草", 148, 8, "#aba076"),
  good("silver", "白银", 520, 8, "#d3d8cd", "箱"),
  good("coffee", "咖啡", 192, 9, "#b29574", "袋"),
  good("indigo", "靛蓝", 230, 10, "#8497be", "匣"),
];
const port = (
  id: string,
  name: string,
  polity: string,
  region: string,
  lon: number,
  lat: number,
  era: number,
  produces: string[],
  demands: string[],
  basin: string,
  danger = 0.15,
): Port => ({
  id,
  name,
  polity,
  region,
  x: lon / 180,
  y: lat / 90,
  era,
  produces,
  demands,
  basin,
  danger,
});
export const ports: Port[] = [
  port(
    "memphis",
    "尼罗河口",
    "古埃及",
    "尼罗河三角洲",
    31.2,
    31.4,
    0,
    ["grain", "linen", "pottery"],
    ["cedar", "copper", "salt"],
    "med",
  ),
  port(
    "ur",
    "乌尔",
    "两河城邦",
    "波斯湾北岸",
    46.1,
    30.9,
    0,
    ["grain", "pottery"],
    ["copper", "cedar", "linen"],
    "gulf",
  ),
  port(
    "dilmun",
    "迪尔蒙",
    "迪尔蒙商人",
    "波斯湾",
    50.6,
    26,
    0,
    ["salt", "copper"],
    ["grain", "pottery", "linen"],
    "gulf",
    0.17,
  ),
  port(
    "lothal",
    "洛塔尔",
    "印度河流域",
    "古吉拉特沿岸",
    72.2,
    22.5,
    0,
    ["linen", "pottery", "salt"],
    ["copper", "cedar", "grain"],
    "indian",
    0.2,
  ),
  port(
    "byblos",
    "比布鲁斯",
    "黎凡特港邦",
    "东地中海",
    35.6,
    34.1,
    0,
    ["cedar", "pottery"],
    ["grain", "copper", "linen"],
    "med",
  ),
  port(
    "magAN",
    "马干",
    "阿曼沿岸聚落",
    "阿曼海湾",
    58.4,
    23.6,
    0,
    ["copper", "salt"],
    ["grain", "linen", "pottery"],
    "gulf",
    0.19,
  ),
  port(
    "crete",
    "克里特",
    "爱琴海港邦",
    "爱琴海",
    25.1,
    35.3,
    1,
    ["oil", "pottery", "wine"],
    ["copper", "tin", "cedar"],
    "med",
  ),
  port(
    "ugarit",
    "乌加里特",
    "黎凡特港邦",
    "东地中海北岸",
    35.8,
    35.6,
    1,
    ["dye", "cedar", "oil"],
    ["grain", "tin", "copper"],
    "med",
  ),
  port(
    "tyre",
    "推罗",
    "腓尼基港邦",
    "黎凡特海岸",
    35.2,
    33.3,
    2,
    ["dye", "glass", "cedar"],
    ["grain", "iron", "wine"],
    "med",
  ),
  port(
    "carthage",
    "迦太基",
    "北非港邦",
    "突尼斯湾",
    10.3,
    36.9,
    2,
    ["oil", "grain", "salt"],
    ["dye", "iron", "glass"],
    "med",
    0.18,
  ),
  port(
    "gadir",
    "加迪尔",
    "伊比利亚港邦",
    "直布罗陀外海",
    -6.3,
    36.5,
    2,
    ["tin", "silver", "salt"],
    ["wine", "oil", "glass"],
    "atlantic",
    0.23,
  ),
  port(
    "alexandria",
    "亚历山大里亚",
    "埃及海贸城市",
    "地中海南岸",
    29.9,
    31.2,
    3,
    ["grain", "glass", "linen"],
    ["silk", "pepper", "cinnamon"],
    "med",
  ),
  port(
    "ostia",
    "奥斯提亚",
    "意大利港城",
    "第勒尼安海",
    12.3,
    41.8,
    3,
    ["wine", "glass", "iron"],
    ["grain", "silk", "pepper"],
    "med",
  ),
  port(
    "berenike",
    "贝勒尼基",
    "红海港城",
    "红海西岸",
    35.5,
    23.9,
    3,
    ["glass", "linen"],
    ["pepper", "silk", "cinnamon"],
    "redsea",
    0.22,
  ),
  port(
    "muziris",
    "穆齐里斯",
    "马拉巴尔港邦",
    "印度西岸",
    76.2,
    10.2,
    3,
    ["pepper", "cinnamon"],
    ["glass", "copper", "wine"],
    "indian",
    0.21,
  ),
  port(
    "constantinople",
    "君士坦丁堡",
    "东罗马商港",
    "博斯普鲁斯海峡",
    29,
    41,
    4,
    ["silk", "glass", "wine"],
    ["grain", "gems", "pepper"],
    "med",
    0.2,
  ),
  port(
    "siraf",
    "西拉夫",
    "波斯海贸城市",
    "波斯湾东岸",
    52.3,
    27.7,
    4,
    ["ivory-sub", "pottery"],
    ["silk", "cinnamon", "grain"],
    "gulf",
    0.2,
  ),
  port(
    "adulis",
    "阿杜利斯",
    "阿克苏姆海港",
    "红海南部",
    39.7,
    15.3,
    4,
    ["salt", "gems"],
    ["linen", "copper", "glass"],
    "redsea",
    0.24,
  ),
  port(
    "guangzhou",
    "广州",
    "岭南商港",
    "中国南海",
    113.3,
    23.1,
    5,
    ["silk", "tea", "porcelain"],
    ["pepper", "ivory-sub", "gems"],
    "china",
    0.22,
  ),
  port(
    "basra",
    "巴士拉",
    "两河海贸城市",
    "波斯湾北岸",
    47.8,
    30.5,
    5,
    ["cotton", "pottery"],
    ["porcelain", "tea", "pepper"],
    "gulf",
  ),
  port(
    "aden",
    "亚丁",
    "阿拉伯商港",
    "亚丁湾",
    45,
    12.8,
    5,
    ["salt", "cotton"],
    ["grain", "silk", "porcelain"],
    "indian",
    0.25,
  ),
  port(
    "palembang",
    "巨港",
    "苏门答腊商港",
    "马六甲海峡南端",
    104.8,
    -3,
    5,
    ["pepper", "gems"],
    ["silk", "porcelain", "cotton"],
    "southeast",
    0.28,
  ),
  port(
    "quanzhou",
    "泉州",
    "福建商港",
    "中国东南沿海",
    118.6,
    24.9,
    6,
    ["porcelain", "silk", "tea"],
    ["cloves", "pepper", "gems"],
    "china",
  ),
  port(
    "calicut",
    "卡利卡特",
    "马拉巴尔商港",
    "印度西岸",
    75.8,
    11.3,
    6,
    ["pepper", "cotton", "cinnamon"],
    ["porcelain", "silk", "cloves"],
    "indian",
    0.23,
  ),
  port(
    "kilwa",
    "基尔瓦",
    "东非海岸商港",
    "斯瓦希里海岸",
    39.5,
    -9,
    6,
    ["gems", "ivory-sub"],
    ["cotton", "porcelain", "iron"],
    "indian",
    0.24,
  ),
  port(
    "venice",
    "威尼斯",
    "威尼斯商人",
    "亚得里亚海",
    12.3,
    45.4,
    6,
    ["glass", "wine"],
    ["silk", "pepper", "cotton"],
    "med",
  ),
  port(
    "hormuz",
    "霍尔木兹",
    "海峡商港",
    "霍尔木兹海峡",
    56.5,
    27.1,
    7,
    ["ivory-sub", "salt"],
    ["silk", "paper", "cloves"],
    "gulf",
    0.3,
  ),
  port(
    "malacca",
    "马六甲",
    "海峡商港",
    "马六甲海峡",
    102.3,
    2.2,
    7,
    ["cloves", "nutmeg", "pepper"],
    ["porcelain", "cotton", "silver"],
    "southeast",
    0.3,
  ),
  port(
    "lisbon",
    "里斯本",
    "葡萄牙商港",
    "伊比利亚大西洋岸",
    -9.1,
    38.7,
    8,
    ["wine", "oil", "iron"],
    ["sugar", "cocoa", "pepper"],
    "atlantic",
    0.24,
  ),
  port(
    "goa",
    "果阿",
    "印度西岸商港",
    "康坎海岸",
    73.8,
    15.5,
    8,
    ["cotton", "pepper", "gems"],
    ["silver", "porcelain", "wine"],
    "indian",
    0.3,
  ),
  port(
    "santo-domingo",
    "圣多明各",
    "加勒比海港",
    "伊斯帕尼奥拉岛",
    -69.9,
    18.5,
    8,
    ["sugar", "cocoa", "tobacco"],
    ["iron", "linen", "wine"],
    "caribbean",
    0.34,
  ),
  port(
    "havana",
    "哈瓦那",
    "加勒比海港",
    "古巴岛北岸",
    -82.4,
    23.1,
    8,
    ["sugar", "tobacco"],
    ["iron", "pottery", "wine"],
    "caribbean",
    0.35,
  ),
  port(
    "veracruz",
    "韦拉克鲁斯",
    "美洲商港",
    "墨西哥湾",
    -96.1,
    19.2,
    8,
    ["silver", "cocoa"],
    ["silk", "iron", "porcelain"],
    "caribbean",
    0.33,
  ),
  port(
    "manila",
    "马尼拉",
    "吕宋商港",
    "菲律宾群岛",
    121,
    14.6,
    9,
    ["silver", "sugar"],
    ["silk", "porcelain", "tea"],
    "southeast",
    0.29,
  ),
  port(
    "yuegang",
    "月港",
    "福建海贸港",
    "中国东南沿海",
    117.8,
    24.4,
    9,
    ["porcelain", "tea", "silk"],
    ["silver", "cloves", "nutmeg"],
    "china",
    0.22,
  ),
  port(
    "amsterdam",
    "阿姆斯特丹",
    "尼德兰商港",
    "北海沿岸",
    4.9,
    52.4,
    9,
    ["iron", "linen", "glass"],
    ["coffee", "tea", "sugar"],
    "atlantic",
    0.23,
  ),
  port(
    "batavia",
    "巴达维亚",
    "爪哇商港",
    "爪哇岛北岸",
    106.8,
    -6.1,
    9,
    ["cloves", "nutmeg", "coffee"],
    ["silver", "cotton", "porcelain"],
    "southeast",
    0.31,
  ),
  port(
    "london",
    "伦敦",
    "不列颠商港",
    "泰晤士河口",
    -0.1,
    51.5,
    10,
    ["iron", "linen", "glass"],
    ["tea", "coffee", "indigo"],
    "atlantic",
    0.22,
  ),
  port(
    "surat",
    "苏拉特",
    "古吉拉特商港",
    "印度西岸",
    72.8,
    21.2,
    10,
    ["indigo", "cotton", "gems"],
    ["silver", "coffee", "porcelain"],
    "indian",
    0.25,
  ),
];
ports.push(...extendedPorts, ...majorPorts);
goods.push(...extendedGoods);
export const goodById = new Map(goods.map((item) => [item.id, item]));
export const portById = new Map(ports.map((item) => [item.id, item]));
const localMarkets = createMarketCatalog(ports, goods);
/** Local sale stock only. Cargo brought from another port can still be sold. */
export function goodsForPort(portId: string, eraIndex: number, sandbox = false): Good[] {
  return (localMarkets.get(portId) ?? []).filter((item) => sandbox || item.era <= eraIndex);
}
export const origins: Origin[] = [
  {
    id: "egypt",
    title: "尼罗河三角洲",
    portId: "memphis",
    region: "古埃及 · 前 3000 年",
    note: "河谷的丰收，是家族的第一笔资本。",
    perk: "谷物与亚麻采购优惠 10%",
    capital: 850,
    goods: { grain: 12, linen: 5 },
    accent: "#c8ac77",
    era: 0,
  },
  {
    id: "mesopotamia",
    title: "两河下游",
    portId: "ur",
    region: "两河城邦 · 前 3000 年",
    note: "账册、陶器与河湾商路。",
    perk: "陶器采购优惠 12%",
    capital: 920,
    goods: { grain: 8, pottery: 4 },
    accent: "#b9996d",
    era: 0,
  },
  {
    id: "levant",
    title: "黎凡特海岸",
    portId: "byblos",
    region: "比布鲁斯 · 前 3000 年",
    note: "以雪松木换取海的另一岸。",
    perk: "雪松木采购优惠 12%",
    capital: 780,
    goods: { cedar: 6, pottery: 4 },
    accent: "#859d7d",
    era: 0,
  },
  {
    id: "dilmun",
    title: "海湾中转地",
    portId: "dilmun",
    region: "迪尔蒙 · 前 3000 年",
    note: "以盐与铜连接两岸的商人。",
    perk: "盐与铜采购优惠 8%",
    capital: 900,
    goods: { salt: 8, copper: 3 },
    accent: "#b3a16f",
    era: 0,
  },
  {
    id: "indus",
    title: "印度河流域",
    portId: "lothal",
    region: "洛塔尔地区 · 前 3000 年",
    note: "陶器与布料，通向远方的港湾。",
    perk: "亚麻与陶器采购优惠 10%",
    capital: 840,
    goods: { linen: 6, pottery: 4 },
    accent: "#93aa88",
    era: 0,
  },
  {
    id: "oman",
    title: "阿曼海岸",
    portId: "magAN",
    region: "马干 · 前 3000 年",
    note: "铜矿与海风养育了这片海岸。",
    perk: "铜采购优惠 12%，航行风险降低",
    capital: 800,
    goods: { copper: 5, salt: 6 },
    accent: "#bcb383",
    era: 0,
  },
];
